//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroTelcome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public bool Isactive { get; set; }
        public bool Isbuisness { get; set; }
        public Nullable<int> Lines  { get; set; }
    
        public virtual Packages Packages { get; set; }
    }
}
